version: '3'

# Глобальные переменные проекта
vars:
  BIN_DIR: '{{.ROOT_DIR}}/bin'
  EASYP: '{{.BIN_DIR}}/easyp'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
  PROTOC_GEN_VALIDATE: '{{.BIN_DIR}}/protoc-gen-validate'
  # Прокси для обхода блокировок proxy.golang.org
  GOPROXY: 'https://goproxy.cn,https://goproxy.io,https://proxy.golang.org,direct'
  # Форматтеры и линтеры
  GOFUMPT_VERSION: 'v0.8.0'
  GCI_VERSION: 'v0.13.6'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  GCI: '{{.BIN_DIR}}/gci'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'

tasks:
  install-tools:
    desc: "Устанавливает инструменты (easyp, protoc-gen-go, protoc-gen-go-grpc) в ./bin/"
    summary: |
      Проверяет наличие инструментов в директории bin.
      Если инструменты не найдены, они будут автоматически установлены.
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        [ -f {{.EASYP}} ] || {
          echo '📦 Устанавливаем easyp...'
          GOBIN={{.BIN_DIR}} go install github.com/easyp-tech/easyp/cmd/easyp@latest
        }
        [ -f {{.PROTOC_GEN_GO}} ] || {
          echo '📦 Устанавливаем protoc-gen-go...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        }
        [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
          echo '📦 Устанавливаем protoc-gen-go-grpc...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        }
    status:
      - test -x {{.EASYP}}
      - test -x {{.PROTOC_GEN_GO}}
      - test -x {{.PROTOC_GEN_GO_GRPC}}

  mod-update:
    desc: "Обновление зависимостей proto через easyp"
    deps: [ install-tools ]
    cmds:
      - '{{.EASYP}} mod update'

  mod-tidy:
    desc: "Очистка и обновление зависимостей Go модуля (go mod tidy)"
    cmds:
      - go mod tidy

  install-validate:
    desc: "Устанавливает protoc-gen-validate"
    summary: |
      Проверяет наличие protoc-gen-validate в директории bin.
      Если инструмент не найден, он будет автоматически установлен.
      
      Примечание: В текущей реализации используется runtime валидация через buf.build/go/protovalidate,
      но protoc-gen-validate может быть полезен для будущего использования или других целей.
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        [ -f {{.PROTOC_GEN_VALIDATE}} ] || {
          echo '📦 Устанавливаем protoc-gen-validate...'
          GOBIN={{.BIN_DIR}} go install github.com/bufbuild/protovalidate/tools/protoc-gen-validate@latest
        }
    status:
      - test -x {{.PROTOC_GEN_VALIDATE}}

  generate:
    desc: "Генерация Go кода из proto файлов"
    deps: [ install-tools, install-validate ]
    cmds:
      - '{{.EASYP}} generate --path proto'

  lint:
    desc: "Линтинг proto файлов"
    deps: [ install-tools ]
    cmds:
      - |
        echo "🔍 Линтинг proto файлов..."
        {{.EASYP}} lint --path proto
        echo "✅ Линтинг proto файлов завершен успешно"

  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    summary: |
      Эта задача проверяет наличие инструментов форматирования кода gofumpt и gci в директории bin.
      Если инструменты не найдены, они будут автоматически установлены с указанными версиями.

      Используется:
        - gofumpt: для форматирования кода Go
        - gci: для сортировки импортов Go
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  format:
    desc: "Форматирует весь проект gofumpt + gci"
    summary: |
      Форматирует все Go-файлы проекта с использованием gofumpt для стандартизации кода
      и gci для сортировки импортов.

      Использует инструменты:
        - gofumpt: для стандартизации форматирования
        - gci: для сортировки импортов по стандартным группам
    deps: [ install-formatters ]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt ..."
        find . -type f -name '*.go' ! -path '*/vendor/*' ! -path '*/bin/*' ! -path '*/pkg/proto/*' ! -path '*/_final/*' ! -path '*/notes-service/*' -exec {{.GOFUMPT}} -extra -w {} +
      - |
        echo "🎯 Сортируем импорты через gci ..."
        find . -type f -name '*.go' ! -path '*/vendor/*' ! -path '*/bin/*' ! -path '*/pkg/proto/*' ! -path '*/_final/*' ! -path '*/notes-service/*' -exec {{.GCI}} write -s standard -s default {} +

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    summary: |
      Проверяет наличие golangci-lint в директории bin.
      Если инструмент не найден, автоматически устанавливает его через go install.

      Устанавливаемая версия: {{.GOLANGCI_LINT_VERSION}}
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        [ -f {{.GOLANGCI_LINT}} ] || {
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  lint:go:
    desc: "Запускает golangci-lint для Go кода"
    summary: |
      Запускает линтер golangci-lint для всего проекта.
      Линтер проверяет код на соответствие стандартам качества и лучшим практикам.
    deps: [ install-golangci-lint ]
    cmds:
      - |
        echo "🔍 Линтинг Go кода..."
        {{.GOLANGCI_LINT}} run ./...
        echo "✅ Линтинг Go кода завершен успешно"

  run:
    desc: "Запуск сервера (через go run, без сборки)"
    cmds:
      - go run cmd/server/main.go

  clean:
    desc: "Очистка артефактов сборки"
    cmds:
      - rm -rf bin/
      - rm -rf pkg/proto/

  test:
    desc: "Запуск тестов"
    cmds:
      - go test ./...

