// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/test/v1/test.proto

package testv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestMessage - тестовое сообщение для проверки валидаций
type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PatternField  string                 `protobuf:"bytes,3,opt,name=pattern_field,json=patternField,proto3" json:"pattern_field,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_proto_test_v1_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_v1_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_proto_test_v1_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TestMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TestMessage) GetPatternField() string {
	if x != nil {
		return x.PatternField
	}
	return ""
}

func (x *TestMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TestMessage) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

// EmptyMessage - сообщение без валидаций
type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_proto_test_v1_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_v1_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_proto_test_v1_test_proto_rawDescGZIP(), []int{1}
}

func (x *EmptyMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_test_v1_test_proto protoreflect.FileDescriptor

const file_proto_test_v1_test_proto_rawDesc = "" +
	"\n" +
	"\x18proto/test/v1/test.proto\x12\atest.v1\x1a\x17validate/validate.proto\"\xc5\x01\n" +
	"\vTestMessage\x12\x1f\n" +
	"\x05title\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18dR\x05title\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x129\n" +
	"\rpattern_field\x18\x03 \x01(\tB\x14\xfaB\x11r\x0f2\r^[A-Z][a-z]+$R\fpatternField\x12\x1e\n" +
	"\x04tags\x18\x04 \x03(\tB\n" +
	"\xfaB\a\x92\x01\x04\b\x01\x10\n" +
	"R\x04tags\x12\x1b\n" +
	"\x03age\x18\x05 \x01(\x05B\t\xfaB\x06\x1a\x04\x18x(\x12R\x03age\"\"\n" +
	"\fEmptyMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB\x10Z\x0etest/v1;testv1b\x06proto3"

var (
	file_proto_test_v1_test_proto_rawDescOnce sync.Once
	file_proto_test_v1_test_proto_rawDescData []byte
)

func file_proto_test_v1_test_proto_rawDescGZIP() []byte {
	file_proto_test_v1_test_proto_rawDescOnce.Do(func() {
		file_proto_test_v1_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_test_v1_test_proto_rawDesc), len(file_proto_test_v1_test_proto_rawDesc)))
	})
	return file_proto_test_v1_test_proto_rawDescData
}

var file_proto_test_v1_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_test_v1_test_proto_goTypes = []any{
	(*TestMessage)(nil),  // 0: test.v1.TestMessage
	(*EmptyMessage)(nil), // 1: test.v1.EmptyMessage
}
var file_proto_test_v1_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_test_v1_test_proto_init() }
func file_proto_test_v1_test_proto_init() {
	if File_proto_test_v1_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_test_v1_test_proto_rawDesc), len(file_proto_test_v1_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_test_v1_test_proto_goTypes,
		DependencyIndexes: file_proto_test_v1_test_proto_depIdxs,
		MessageInfos:      file_proto_test_v1_test_proto_msgTypes,
	}.Build()
	File_proto_test_v1_test_proto = out.File
	file_proto_test_v1_test_proto_goTypes = nil
	file_proto_test_v1_test_proto_depIdxs = nil
}
