// Code generated by protoc-gen-template-validate (compatible with protoc-gen-simple-validate). DO NOT EDIT.
// source: proto/test/v1/test.proto

package testv1

import (
	fmt "fmt"
	regexp "regexp"
)

// Validate validates all fields in TestMessage
func (t *TestMessage) Validate() error {
	if len(t.Title) < 3 {
		return fmt.Errorf("field Title must be at least 3 characters")
	}
	if len(t.Title) > 100 {
		return fmt.Errorf("field Title must be at most 100 characters")
	}
	if !isValidEmail(t.Email) {
		return fmt.Errorf("field Email must be a valid email address")
	}
	patternPatternField := regexp.MustCompile("^[A-Z][a-z]+$")
	if !patternPatternField.MatchString(t.PatternField) {
		return fmt.Errorf("field PatternField does not match required pattern")
	}
	if len(t.Tags) < 1 {
		return fmt.Errorf("field Tags must have at least 1 items")
	}
	if len(t.Tags) > 10 {
		return fmt.Errorf("field Tags must have at most 10 items")
	}
	return nil
}

// Validate validates all fields in EmptyMessage
func (e *EmptyMessage) Validate() error {
	return nil
}

// isValidEmail checks if the email string is valid
func isValidEmail(email string) bool {
	emailRegex := regexp.MustCompile(`^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$`)
	return emailRegex.MatchString(email)
}
