// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/notes/v1/notes.proto

// Package notes.v1 содержит API для работы с заметками

package notesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на создание заметки
type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`     // Заголовок заметки (обязательное, минимум 5 символов, максимум 255)
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Содержание заметки (обязательное, минимум 10 символов)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Ответ с созданной заметкой
type CreateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *Note                  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteResponse) Reset() {
	*x = CreateNoteResponse{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteResponse) ProtoMessage() {}

func (x *CreateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNoteResponse) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

// Запрос на получение заметки по UUID
type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID заметки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{2}
}

func (x *GetNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ с заметкой
type GetNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *Note                  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteResponse) Reset() {
	*x = GetNoteResponse{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteResponse) ProtoMessage() {}

func (x *GetNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteResponse.ProtoReflect.Descriptor instead.
func (*GetNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{3}
}

func (x *GetNoteResponse) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

// Запрос на получение списка заметок
type ListNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesRequest) Reset() {
	*x = ListNotesRequest{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesRequest) ProtoMessage() {}

func (x *ListNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesRequest.ProtoReflect.Descriptor instead.
func (*ListNotesRequest) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{4}
}

// Ответ со списком заметок
type ListNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*Note                `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesResponse) Reset() {
	*x = ListNotesResponse{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesResponse) ProtoMessage() {}

func (x *ListNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesResponse.ProtoReflect.Descriptor instead.
func (*ListNotesResponse) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{5}
}

func (x *ListNotesResponse) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

// Запрос на обновление заметки
type UpdateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // UUID заметки
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`     // Новый заголовок (опционально)
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // Новое содержание (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteRequest) Reset() {
	*x = UpdateNoteRequest{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRequest) ProtoMessage() {}

func (x *UpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Ответ с обновленной заметкой
type UpdateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *Note                  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteResponse) Reset() {
	*x = UpdateNoteResponse{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteResponse) ProtoMessage() {}

func (x *UpdateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNoteResponse) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

// Запрос на удаление заметки
type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID заметки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ на удаление заметки
type DeleteNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteResponse) Reset() {
	*x = DeleteNoteResponse{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteResponse) ProtoMessage() {}

func (x *DeleteNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteResponse.ProtoReflect.Descriptor instead.
func (*DeleteNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{9}
}

// Note представляет заметку
type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // UUID заметки
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                          // Заголовок заметки
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                      // Содержание заметки
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Дата создания
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Дата последнего обновления
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{10}
}

func (x *Note) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Note) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Note) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ErrorDetails содержит детальную информацию об ошибке
type ErrorDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Reason            string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`                                                  // Причина ошибки
	InternalErrorCode string                 `protobuf:"bytes,2,opt,name=internal_error_code,json=internalErrorCode,proto3" json:"internal_error_code,omitempty"` // Внутренний код ошибки
	NoteId            string                 `protobuf:"bytes,3,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`                                    // ID заметки, связанной с ошибкой
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorDetails) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorDetails) GetInternalErrorCode() string {
	if x != nil {
		return x.InternalErrorCode
	}
	return ""
}

func (x *ErrorDetails) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

// Запрос на подписку на события
type SubscribeToEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToEventsRequest) Reset() {
	*x = SubscribeToEventsRequest{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToEventsRequest) ProtoMessage() {}

func (x *SubscribeToEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{12}
}

// Ответ со стримом событий
type EventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventResponse_HealthCheck
	//	*EventResponse_NoteCreated
	Event         isEventResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{13}
}

func (x *EventResponse) GetEvent() isEventResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventResponse) GetHealthCheck() *HealthCheck {
	if x != nil {
		if x, ok := x.Event.(*EventResponse_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

func (x *EventResponse) GetNoteCreated() *NoteCreatedEvent {
	if x != nil {
		if x, ok := x.Event.(*EventResponse_NoteCreated); ok {
			return x.NoteCreated
		}
	}
	return nil
}

type isEventResponse_Event interface {
	isEventResponse_Event()
}

type EventResponse_HealthCheck struct {
	// Приветственное сообщение или health-check
	HealthCheck *HealthCheck `protobuf:"bytes,1,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

type EventResponse_NoteCreated struct {
	// Событие создания новой заметки
	NoteCreated *NoteCreatedEvent `protobuf:"bytes,2,opt,name=note_created,json=noteCreated,proto3,oneof"`
}

func (*EventResponse_HealthCheck) isEventResponse_Event() {}

func (*EventResponse_NoteCreated) isEventResponse_Event() {}

// HealthCheck сообщение для поддержания соединения
type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`     // Сообщение health-check
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Временная метка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheck) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Событие создания новой заметки
type NoteCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"` // ID созданной заметки
	Note          *Note                  `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`                   // Опционально: можно отправлять только ID или всю заметку
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteCreatedEvent) Reset() {
	*x = NoteCreatedEvent{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteCreatedEvent) ProtoMessage() {}

func (x *NoteCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteCreatedEvent.ProtoReflect.Descriptor instead.
func (*NoteCreatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{15}
}

func (x *NoteCreatedEvent) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteCreatedEvent) GetNote() *Note {
	if x != nil {
		return x.Note
	}
	return nil
}

// Запрос на загрузку метрики (клиентский стриминг)
type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"` // Значение метрики
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     // Опционально: название метрики
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{16}
}

func (x *MetricRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Ответ со статистикой по метрикам
type SummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           float64                `protobuf:"fixed64,1,opt,name=sum,proto3" json:"sum,omitempty"`         // Сумма всех метрик
	Average       float64                `protobuf:"fixed64,2,opt,name=average,proto3" json:"average,omitempty"` // Среднее значение
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`      // Количество метрик
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{17}
}

func (x *SummaryResponse) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *SummaryResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *SummaryResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Сообщение в чате (bidirectional streaming)
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // ID для корреляции запросов и ответов
	// Types that are valid to be assigned to Content:
	//
	//	*ChatMessage_TextMessage
	//	*ChatMessage_Error
	Content       isChatMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{18}
}

func (x *ChatMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ChatMessage) GetContent() isChatMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatMessage) GetTextMessage() *ChatTextMessage {
	if x != nil {
		if x, ok := x.Content.(*ChatMessage_TextMessage); ok {
			return x.TextMessage
		}
	}
	return nil
}

func (x *ChatMessage) GetError() *ChatError {
	if x != nil {
		if x, ok := x.Content.(*ChatMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isChatMessage_Content interface {
	isChatMessage_Content()
}

type ChatMessage_TextMessage struct {
	// Обычное текстовое сообщение
	TextMessage *ChatTextMessage `protobuf:"bytes,2,opt,name=text_message,json=textMessage,proto3,oneof"`
}

type ChatMessage_Error struct {
	// Бизнесовая ошибка (не разрывающая соединение)
	Error *ChatError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ChatMessage_TextMessage) isChatMessage_Content() {}

func (*ChatMessage_Error) isChatMessage_Content() {}

// Текстовое сообщение в чате
type ChatTextMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`           // Текст сообщения
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Временная метка сообщения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatTextMessage) Reset() {
	*x = ChatTextMessage{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTextMessage) ProtoMessage() {}

func (x *ChatTextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTextMessage.ProtoReflect.Descriptor instead.
func (*ChatTextMessage) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{19}
}

func (x *ChatTextMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatTextMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Ошибка в чате (бизнесовая, не разрывающая соединение)
type ChatError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // Код ошибки (например, "VALIDATION_ERROR", "RATE_LIMIT")
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Сообщение об ошибке
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"` // Дополнительные детали ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatError) Reset() {
	*x = ChatError{}
	mi := &file_proto_notes_v1_notes_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatError) ProtoMessage() {}

func (x *ChatError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notes_v1_notes_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatError.ProtoReflect.Descriptor instead.
func (*ChatError) Descriptor() ([]byte, []int) {
	return file_proto_notes_v1_notes_proto_rawDescGZIP(), []int{20}
}

func (x *ChatError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ChatError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_proto_notes_v1_notes_proto protoreflect.FileDescriptor

const file_proto_notes_v1_notes_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/notes/v1/notes.proto\x12\bnotes.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"X\n" +
	"\x11CreateNoteRequest\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x05\x18\xff\x01R\x05title\x12!\n" +
	"\acontent\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\n" +
	"R\acontent\"8\n" +
	"\x12CreateNoteResponse\x12\"\n" +
	"\x04note\x18\x01 \x01(\v2\x0e.notes.v1.NoteR\x04note\" \n" +
	"\x0eGetNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x0fGetNoteResponse\x12\"\n" +
	"\x04note\x18\x01 \x01(\v2\x0e.notes.v1.NoteR\x04note\"\x12\n" +
	"\x10ListNotesRequest\"9\n" +
	"\x11ListNotesResponse\x12$\n" +
	"\x05notes\x18\x01 \x03(\v2\x0e.notes.v1.NoteR\x05notes\"S\n" +
	"\x11UpdateNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"8\n" +
	"\x12UpdateNoteResponse\x12\"\n" +
	"\x04note\x18\x01 \x01(\v2\x0e.notes.v1.NoteR\x04note\"#\n" +
	"\x11DeleteNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteNoteResponse\"\xbc\x01\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"o\n" +
	"\fErrorDetails\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12.\n" +
	"\x13internal_error_code\x18\x02 \x01(\tR\x11internalErrorCode\x12\x17\n" +
	"\anote_id\x18\x03 \x01(\tR\x06noteId\"\x1a\n" +
	"\x18SubscribeToEventsRequest\"\x95\x01\n" +
	"\rEventResponse\x12:\n" +
	"\fhealth_check\x18\x01 \x01(\v2\x15.notes.v1.HealthCheckH\x00R\vhealthCheck\x12?\n" +
	"\fnote_created\x18\x02 \x01(\v2\x1a.notes.v1.NoteCreatedEventH\x00R\vnoteCreatedB\a\n" +
	"\x05event\"a\n" +
	"\vHealthCheck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"O\n" +
	"\x10NoteCreatedEvent\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\"\n" +
	"\x04note\x18\x02 \x01(\v2\x0e.notes.v1.NoteR\x04note\"9\n" +
	"\rMetricRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"S\n" +
	"\x0fSummaryResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x01R\x03sum\x12\x18\n" +
	"\aaverage\x18\x02 \x01(\x01R\aaverage\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"\xac\x01\n" +
	"\vChatMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12>\n" +
	"\ftext_message\x18\x02 \x01(\v2\x19.notes.v1.ChatTextMessageH\x00R\vtextMessage\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x13.notes.v1.ChatErrorH\x00R\x05errorB\t\n" +
	"\acontent\"_\n" +
	"\x0fChatTextMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"S\n" +
	"\tChatError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails2\xc4\x04\n" +
	"\fNotesService\x12G\n" +
	"\n" +
	"CreateNote\x12\x1b.notes.v1.CreateNoteRequest\x1a\x1c.notes.v1.CreateNoteResponse\x12>\n" +
	"\aGetNote\x12\x18.notes.v1.GetNoteRequest\x1a\x19.notes.v1.GetNoteResponse\x12D\n" +
	"\tListNotes\x12\x1a.notes.v1.ListNotesRequest\x1a\x1b.notes.v1.ListNotesResponse\x12G\n" +
	"\n" +
	"UpdateNote\x12\x1b.notes.v1.UpdateNoteRequest\x1a\x1c.notes.v1.UpdateNoteResponse\x12G\n" +
	"\n" +
	"DeleteNote\x12\x1b.notes.v1.DeleteNoteRequest\x1a\x1c.notes.v1.DeleteNoteResponse\x12R\n" +
	"\x11SubscribeToEvents\x12\".notes.v1.SubscribeToEventsRequest\x1a\x17.notes.v1.EventResponse0\x01\x12E\n" +
	"\rUploadMetrics\x12\x17.notes.v1.MetricRequest\x1a\x19.notes.v1.SummaryResponse(\x01\x128\n" +
	"\x04Chat\x12\x15.notes.v1.ChatMessage\x1a\x15.notes.v1.ChatMessage(\x010\x01B\x12Z\x10notes/v1;notesv1b\x06proto3"

var (
	file_proto_notes_v1_notes_proto_rawDescOnce sync.Once
	file_proto_notes_v1_notes_proto_rawDescData []byte
)

func file_proto_notes_v1_notes_proto_rawDescGZIP() []byte {
	file_proto_notes_v1_notes_proto_rawDescOnce.Do(func() {
		file_proto_notes_v1_notes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notes_v1_notes_proto_rawDesc), len(file_proto_notes_v1_notes_proto_rawDesc)))
	})
	return file_proto_notes_v1_notes_proto_rawDescData
}

var file_proto_notes_v1_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_notes_v1_notes_proto_goTypes = []any{
	(*CreateNoteRequest)(nil),        // 0: notes.v1.CreateNoteRequest
	(*CreateNoteResponse)(nil),       // 1: notes.v1.CreateNoteResponse
	(*GetNoteRequest)(nil),           // 2: notes.v1.GetNoteRequest
	(*GetNoteResponse)(nil),          // 3: notes.v1.GetNoteResponse
	(*ListNotesRequest)(nil),         // 4: notes.v1.ListNotesRequest
	(*ListNotesResponse)(nil),        // 5: notes.v1.ListNotesResponse
	(*UpdateNoteRequest)(nil),        // 6: notes.v1.UpdateNoteRequest
	(*UpdateNoteResponse)(nil),       // 7: notes.v1.UpdateNoteResponse
	(*DeleteNoteRequest)(nil),        // 8: notes.v1.DeleteNoteRequest
	(*DeleteNoteResponse)(nil),       // 9: notes.v1.DeleteNoteResponse
	(*Note)(nil),                     // 10: notes.v1.Note
	(*ErrorDetails)(nil),             // 11: notes.v1.ErrorDetails
	(*SubscribeToEventsRequest)(nil), // 12: notes.v1.SubscribeToEventsRequest
	(*EventResponse)(nil),            // 13: notes.v1.EventResponse
	(*HealthCheck)(nil),              // 14: notes.v1.HealthCheck
	(*NoteCreatedEvent)(nil),         // 15: notes.v1.NoteCreatedEvent
	(*MetricRequest)(nil),            // 16: notes.v1.MetricRequest
	(*SummaryResponse)(nil),          // 17: notes.v1.SummaryResponse
	(*ChatMessage)(nil),              // 18: notes.v1.ChatMessage
	(*ChatTextMessage)(nil),          // 19: notes.v1.ChatTextMessage
	(*ChatError)(nil),                // 20: notes.v1.ChatError
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
}
var file_proto_notes_v1_notes_proto_depIdxs = []int32{
	10, // 0: notes.v1.CreateNoteResponse.note:type_name -> notes.v1.Note
	10, // 1: notes.v1.GetNoteResponse.note:type_name -> notes.v1.Note
	10, // 2: notes.v1.ListNotesResponse.notes:type_name -> notes.v1.Note
	10, // 3: notes.v1.UpdateNoteResponse.note:type_name -> notes.v1.Note
	21, // 4: notes.v1.Note.created_at:type_name -> google.protobuf.Timestamp
	21, // 5: notes.v1.Note.updated_at:type_name -> google.protobuf.Timestamp
	14, // 6: notes.v1.EventResponse.health_check:type_name -> notes.v1.HealthCheck
	15, // 7: notes.v1.EventResponse.note_created:type_name -> notes.v1.NoteCreatedEvent
	21, // 8: notes.v1.HealthCheck.timestamp:type_name -> google.protobuf.Timestamp
	10, // 9: notes.v1.NoteCreatedEvent.note:type_name -> notes.v1.Note
	19, // 10: notes.v1.ChatMessage.text_message:type_name -> notes.v1.ChatTextMessage
	20, // 11: notes.v1.ChatMessage.error:type_name -> notes.v1.ChatError
	21, // 12: notes.v1.ChatTextMessage.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 13: notes.v1.NotesService.CreateNote:input_type -> notes.v1.CreateNoteRequest
	2,  // 14: notes.v1.NotesService.GetNote:input_type -> notes.v1.GetNoteRequest
	4,  // 15: notes.v1.NotesService.ListNotes:input_type -> notes.v1.ListNotesRequest
	6,  // 16: notes.v1.NotesService.UpdateNote:input_type -> notes.v1.UpdateNoteRequest
	8,  // 17: notes.v1.NotesService.DeleteNote:input_type -> notes.v1.DeleteNoteRequest
	12, // 18: notes.v1.NotesService.SubscribeToEvents:input_type -> notes.v1.SubscribeToEventsRequest
	16, // 19: notes.v1.NotesService.UploadMetrics:input_type -> notes.v1.MetricRequest
	18, // 20: notes.v1.NotesService.Chat:input_type -> notes.v1.ChatMessage
	1,  // 21: notes.v1.NotesService.CreateNote:output_type -> notes.v1.CreateNoteResponse
	3,  // 22: notes.v1.NotesService.GetNote:output_type -> notes.v1.GetNoteResponse
	5,  // 23: notes.v1.NotesService.ListNotes:output_type -> notes.v1.ListNotesResponse
	7,  // 24: notes.v1.NotesService.UpdateNote:output_type -> notes.v1.UpdateNoteResponse
	9,  // 25: notes.v1.NotesService.DeleteNote:output_type -> notes.v1.DeleteNoteResponse
	13, // 26: notes.v1.NotesService.SubscribeToEvents:output_type -> notes.v1.EventResponse
	17, // 27: notes.v1.NotesService.UploadMetrics:output_type -> notes.v1.SummaryResponse
	18, // 28: notes.v1.NotesService.Chat:output_type -> notes.v1.ChatMessage
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_notes_v1_notes_proto_init() }
func file_proto_notes_v1_notes_proto_init() {
	if File_proto_notes_v1_notes_proto != nil {
		return
	}
	file_proto_notes_v1_notes_proto_msgTypes[13].OneofWrappers = []any{
		(*EventResponse_HealthCheck)(nil),
		(*EventResponse_NoteCreated)(nil),
	}
	file_proto_notes_v1_notes_proto_msgTypes[18].OneofWrappers = []any{
		(*ChatMessage_TextMessage)(nil),
		(*ChatMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notes_v1_notes_proto_rawDesc), len(file_proto_notes_v1_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notes_v1_notes_proto_goTypes,
		DependencyIndexes: file_proto_notes_v1_notes_proto_depIdxs,
		MessageInfos:      file_proto_notes_v1_notes_proto_msgTypes,
	}.Build()
	File_proto_notes_v1_notes_proto = out.File
	file_proto_notes_v1_notes_proto_goTypes = nil
	file_proto_notes_v1_notes_proto_depIdxs = nil
}
