// Code generated by protoc-gen-template-validate (compatible with protoc-gen-simple-validate). DO NOT EDIT.
// source: proto/notes/v1/notes.proto

package notesv1

import (
	fmt "fmt"
	regexp "regexp"
)

// Validate validates all fields in CreateNoteRequest
func (c *CreateNoteRequest) Validate() error {
	if len(c.Title) < 5 {
		return fmt.Errorf("field Title must be at least 5 characters")
	}
	if len(c.Title) > 255 {
		return fmt.Errorf("field Title must be at most 255 characters")
	}
	if len(c.Content) < 10 {
		return fmt.Errorf("field Content must be at least 10 characters")
	}
	if !isValidEmail(c.Email) {
		return fmt.Errorf("field Email must be a valid email address")
	}
	return nil
}

// Validate validates all fields in CreateNoteResponse
func (c *CreateNoteResponse) Validate() error {
	return nil
}

// Validate validates all fields in GetNoteRequest
func (g *GetNoteRequest) Validate() error {
	return nil
}

// Validate validates all fields in GetNoteResponse
func (g *GetNoteResponse) Validate() error {
	return nil
}

// Validate validates all fields in ListNotesRequest
func (l *ListNotesRequest) Validate() error {
	return nil
}

// Validate validates all fields in ListNotesResponse
func (l *ListNotesResponse) Validate() error {
	return nil
}

// Validate validates all fields in UpdateNoteRequest
func (u *UpdateNoteRequest) Validate() error {
	return nil
}

// Validate validates all fields in UpdateNoteResponse
func (u *UpdateNoteResponse) Validate() error {
	return nil
}

// Validate validates all fields in DeleteNoteRequest
func (d *DeleteNoteRequest) Validate() error {
	return nil
}

// Validate validates all fields in DeleteNoteResponse
func (d *DeleteNoteResponse) Validate() error {
	return nil
}

// Validate validates all fields in Note
func (n *Note) Validate() error {
	return nil
}

// Validate validates all fields in ErrorDetails
func (e *ErrorDetails) Validate() error {
	return nil
}

// Validate validates all fields in SubscribeToEventsRequest
func (s *SubscribeToEventsRequest) Validate() error {
	return nil
}

// Validate validates all fields in EventResponse
func (e *EventResponse) Validate() error {
	return nil
}

// Validate validates all fields in HealthCheck
func (h *HealthCheck) Validate() error {
	return nil
}

// Validate validates all fields in NoteCreatedEvent
func (n *NoteCreatedEvent) Validate() error {
	return nil
}

// Validate validates all fields in MetricRequest
func (m *MetricRequest) Validate() error {
	return nil
}

// Validate validates all fields in SummaryResponse
func (s *SummaryResponse) Validate() error {
	return nil
}

// Validate validates all fields in ChatMessage
func (c *ChatMessage) Validate() error {
	return nil
}

// Validate validates all fields in ChatTextMessage
func (c *ChatTextMessage) Validate() error {
	return nil
}

// Validate validates all fields in ChatError
func (c *ChatError) Validate() error {
	return nil
}

// isValidEmail checks if the email string is valid
func isValidEmail(email string) bool {
	emailRegex := regexp.MustCompile(`^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$`)
	return emailRegex.MatchString(email)
}
